#!/usr/bin/env python3
"""Generate the README/Metadata documents for the Honkai: Star Rail glossary."""

from __future__ import annotations

import json
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_hsr_glossary import CATEGORIES, CATEGORY_LABELS, LANG_ORDER  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
GLOSSARY = ROOT / "hsr-glossary"
TOOLS = ROOT / "tools"

LANG_LABELS = {
    "zh-CN": "简体中文", "zh-TW": "繁體中文", "en-US": "English", "ja-JP": "日本語",
    "ko-KR": "한국어", "fr-FR": "Français", "de-DE": "Deutsch", "es-ES": "Español",
    "ru-RU": "Русский", "pt-PT": "Português", "id-ID": "Bahasa Indonesia",
    "th-TH": "ไทย", "vi-VN": "Tiếng Việt",
}


def load(path: Path, default):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return default



LANG_PACK = {
    "zh-CN": {
        "title": "崩坏：星穹铁道（Honkai: Star Rail）术语库 — {lang_label}（`{lang}`）",
        "nav": "[← 返回游戏总说明](../../README.md) ｜ [← hsr-glossary 子库说明](../README.md)",
        "intro": "本目录是**以 `{lang}`（{lang_label}）为目标语言**的星穹铁道术语库，共 **{ncat}** 个分类 CSV、**{rows:,}** 行对照。所有 CSV 的 `tgt_lng` 列固定为 `{lang}`；`source` 列收录其余语言的官方本地化写法，因此同一条游戏文本可以从任意一种语言匹配到本语言的译名。",
        "files_head": "文件",
        "files_intro": "本目录为**扁平结构**，{ncat} 个分类 CSV 直接放在本目录下：",
        "cols": ("文件", "分类", "本语言记录数"),
        "notes_head": "说明",
        "bullets": [
            "译文来源：游戏客户端本地化文本（TextMap / ExcelOutput），按同一文本键对齐，不是二次翻译。",
            "目标语言缺少该文本键时不会生成记录，也不会用机器翻译补全。",
            "同一文本键在不同语境下可能出现多种译法，全部保留，不做人工取舍。",
            "数据由 `../../tools/build_hsr_glossary.py` 生成，可重新运行复现。",
        ],
    },
    "zh-TW": {
        "title": "崩壞：星穹鐵道（Honkai: Star Rail）術語庫 — {lang_label}（`{lang}`）",
        "nav": "[← 返回遊戲總說明](../../README.md) ｜ [← hsr-glossary 子庫說明](../README.md)",
        "intro": "本目錄是**以 `{lang}`（{lang_label}）為目標語言**的星穹鐵道術語庫，共 **{ncat}** 個分類 CSV、**{rows:,}** 行對照。所有 CSV 的 `tgt_lng` 欄固定為 `{lang}`；`source` 欄收錄其餘語言的官方在地化寫法，因此同一條遊戲文本可以從任一種語言對應到本語言的譯名。",
        "files_head": "檔案",
        "files_intro": "本目錄為**扁平結構**，{ncat} 個分類 CSV 直接放在本目錄下：",
        "cols": ("檔案", "分類", "本語言記錄數"),
        "notes_head": "說明",
        "bullets": [
            "譯文來源：遊戲客戶端在地化文本（TextMap / ExcelOutput），以同一文本鍵對齊，不是二次翻譯。",
            "目標語言缺少該文本鍵時不會產生記錄，也不會以機器翻譯補齊。",
            "同一文本鍵在不同語境下可能有多種譯法，全部保留。",
            "資料由 `../../tools/build_hsr_glossary.py` 產生，可重新執行復現。",
        ],
    },
    "en-US": {
        "title": "Honkai: Star Rail Terminology Database — {lang_label} (`{lang}`)",
        "nav": "[← Back to the game overview](../../README.md) ｜ [← hsr-glossary sub-library](../README.md)",
        "intro": "This directory holds the Honkai: Star Rail terminology database with **`{lang}` ({lang_label}) as the target language**: **{ncat}** category CSVs and **{rows:,}** comparison rows. The `tgt_lng` column is always `{lang}` and the `source` column carries the official localization of every other language, so any source language can be matched to this language.",
        "files_head": "Files",
        "files_intro": "The directory is flat: all {ncat} category CSVs live directly here.",
        "cols": ("File", "Category", "Rows in this language"),
        "notes_head": "Notes",
        "bullets": [
            "Targets come from the game client localization (TextMap / ExcelOutput), aligned by the same text key — no second-hand translation.",
            "When the target language is missing a key, no row is generated and nothing is machine translated.",
            "A key can have several official wordings in different contexts; all of them are kept.",
            "Generated by `../../tools/build_hsr_glossary.py` and fully reproducible.",
        ],
    },
    "ja-JP": {
        "title": "『崩壊：スターレイル』用語集 — {lang_label}（`{lang}`）",
        "nav": "[← ゲーム全体の説明に戻る](../../README.md) ｜ [← hsr-glossary の説明](../README.md)",
        "intro": "本ディレクトリは **`{lang}`（{lang_label}）を対象言語**とする『崩壊：スターレイル』用語集です。**{ncat}** 個のカテゴリ CSV、**{rows:,}** 行の対訳を収録しています。`tgt_lng` 列は常に `{lang}`、`source` 列には他言語の公式ローカライズ文が入るため、どの言語からでも本言語の訳語に一致させられます。",
        "files_head": "ファイル",
        "files_intro": "本ディレクトリは**フラット構造**で、{ncat} 個のカテゴリ CSV が直接置かれています：",
        "cols": ("ファイル", "カテゴリ", "本言語の行数"),
        "notes_head": "注意",
        "bullets": [
            "訳文はゲームクライアントのローカライズテキスト（TextMap / ExcelOutput）を同一テキストキーで対応付けたもので、二次翻訳ではありません。",
            "対象言語にテキストが無い場合はレコードを生成せず、機械翻訳での補完も行いません。",
            "同じテキストキーでも文脈によって複数の訳語があり得るため、すべて保持します。",
            "`../../tools/build_hsr_glossary.py` で生成でき、再現可能です。",
        ],
    },
    "ko-KR": {
        "title": "붕괴: 스타레일(Honkai: Star Rail) 용어집 — {lang_label}(`{lang}`)",
        "nav": "[← 게임 전체 설명으로](../../README.md) ｜ [← hsr-glossary 안내](../README.md)",
        "intro": "이 디렉터리는 **`{lang}`({lang_label})을 대상 언어로 하는** 붕괴: 스타레일 용어집입니다. **{ncat}**개 분류 CSV, **{rows:,}**행의 대역을 수록했습니다. `tgt_lng` 열은 항상 `{lang}`이며, `source` 열에는 다른 언어의 공식 현지화 텍스트가 들어가므로 어떤 언어에서도 이 언어의 표기를 찾을 수 있습니다.",
        "files_head": "파일",
        "files_intro": "이 디렉터리는 **평면 구조**이며, {ncat}개 분류 CSV가 바로 있습니다:",
        "cols": ("파일", "분류", "이 언어의 행 수"),
        "notes_head": "참고",
        "bullets": [
            "번역문은 게임 클라이언트 현지화 텍스트(TextMap / ExcelOutput)를 동일한 텍스트 키로 정렬한 것이며, 2차 번역이 아닙니다.",
            "대상 언어에 해당 텍스트가 없으면 레코드를 만들지 않으며, 기계 번역으로 채우지 않습니다.",
            "같은 텍스트 키라도 문맥에 따라 여러 표기가 있을 수 있고, 모두 유지합니다.",
            "`../../tools/build_hsr_glossary.py` 로 생성되며 재현 가능합니다.",
        ],
    },
    "fr-FR": {
        "title": "Base terminologique Honkai: Star Rail — {lang_label} (`{lang}`)",
        "nav": "[← Retour à la présentation du jeu](../../README.md) ｜ [← sous-bibliothèque hsr-glossary](../README.md)",
        "intro": "Ce répertoire contient la base terminologique Honkai: Star Rail avec **`{lang}` ({lang_label}) comme langue cible** : **{ncat}** fichiers CSV catégoriels et **{rows:,}** lignes d’appariement. La colonne `tgt_lng` vaut toujours `{lang}` et la colonne `source` contient la localisation officielle de chaque autre langue.",
        "files_head": "Fichiers",
        "files_intro": "Le répertoire est **plat** : les {ncat} CSV catégoriels sont directement ici.",
        "cols": ("Fichier", "Catégorie", "Lignes dans cette langue"),
        "notes_head": "Remarques",
        "bullets": [
            "Les textes proviennent de la localisation du client (TextMap / ExcelOutput), alignés par la même clé de texte — aucune traduction de seconde main.",
            "Si la langue cible n’a pas de texte pour une clé, aucune ligne n’est créée et rien n’est traduit automatiquement.",
            "Une même clé peut avoir plusieurs formulations officielles selon le contexte ; toutes sont conservées.",
            "Généré par `../../tools/build_hsr_glossary.py`, entièrement reproductible.",
        ],
    },
    "de-DE": {
        "title": "Honkai: Star Rail Terminologiedatenbank — {lang_label} (`{lang}`)",
        "nav": "[← Zurück zur Spielübersicht](../../README.md) ｜ [← hsr-glossary Unterbibliothek](../README.md)",
        "intro": "Dieses Verzeichnis enthält die Honkai-Star-Rail-Terminologiedatenbank mit **`{lang}` ({lang_label}) als Zielsprache**: **{ncat}** Kategorie-CSVs und **{rows:,}** Vergleichszeilen. Die Spalte `tgt_lng` ist immer `{lang}`, die Spalte `source` enthält die offizielle Lokalisierung jeder anderen Sprache.",
        "files_head": "Dateien",
        "files_intro": "Das Verzeichnis ist **flach aufgebaut**: die {ncat} Kategorie-CSVs liegen direkt hier.",
        "cols": ("Datei", "Kategorie", "Zeilen in dieser Sprache"),
        "notes_head": "Hinweise",
        "bullets": [
            "Die Zieltexte stammen aus der Client-Lokalisierung (TextMap / ExcelOutput) und sind über denselben Textschlüssel ausgerichtet — keine Zweitübersetzung.",
            "Fehlt der Zielsprache ein Text, wird kein Eintrag erzeugt und nichts maschinell übersetzt.",
            "Derselbe Textschlüssel kann je nach Kontext mehrere offizielle Formulierungen haben; alle bleiben erhalten.",
            "Generiert mit `../../tools/build_hsr_glossary.py`, vollständig reproduzierbar.",
        ],
    },
    "es-ES": {
        "title": "Base de terminología de Honkai: Star Rail — {lang_label} (`{lang}`)",
        "nav": "[← Volver a la descripción del juego](../../README.md) ｜ [← subbiblioteca hsr-glossary](../README.md)",
        "intro": "Este directorio contiene la base de terminología de Honkai: Star Rail con **`{lang}` ({lang_label}) como idioma de destino**: **{ncat}** CSV de categorías y **{rows:,}** filas de correspondencia. La columna `tgt_lng` es siempre `{lang}` y la columna `source` incluye la localización oficial de los demás idiomas.",
        "files_head": "Archivos",
        "files_intro": "El directorio es **plano**: los {ncat} CSV de categorías están directamente aquí.",
        "cols": ("Archivo", "Categoría", "Filas en este idioma"),
        "notes_head": "Notas",
        "bullets": [
            "Los textos provienen de la localización del cliente (TextMap / ExcelOutput), alineados por la misma clave de texto; no son traducciones de segunda mano.",
            "Si el idioma de destino no tiene texto para una clave, no se genera ninguna fila ni se rellena con traducción automática.",
            "Una misma clave puede tener varias formas oficiales según el contexto; se conservan todas.",
            "Generado con `../../tools/build_hsr_glossary.py`, totalmente reproducible.",
        ],
    },
    "ru-RU": {
        "title": "Глоссарий Honkai: Star Rail — {lang_label} (`{lang}`)",
        "nav": "[← Вернуться к общему описанию](../../README.md) ｜ [← подбиблиотека hsr-glossary](../README.md)",
        "intro": "В этом каталоге находится глоссарий Honkai: Star Rail с **целевым языком `{lang}` ({lang_label})**: **{ncat}** CSV по категориям и **{rows:,}** строк сопоставления. Столбец `tgt_lng` всегда равен `{lang}`, а `source` содержит официальную локализацию остальных языков.",
        "files_head": "Файлы",
        "files_intro": "Каталог **плоский**: все {ncat} CSV по категориям лежат здесь.",
        "cols": ("Файл", "Категория", "Строк на этом языке"),
        "notes_head": "Примечания",
        "bullets": [
            "Тексты взяты из клиентской локализации (TextMap / ExcelOutput) и сопоставлены по одному и тому же текстовому ключу — это не вторичный перевод.",
            "Если в целевом языке текст отсутствует, строка не создаётся и машинный перевод не подставляется.",
            "Один и тот же ключ может иметь несколько официальных формулировок; сохраняются все.",
            "Сгенерировано с помощью `../../tools/build_hsr_glossary.py`, воспроизводимо.",
        ],
    },
    "pt-PT": {
        "title": "Base de terminologia de Honkai: Star Rail — {lang_label} (`{lang}`)",
        "nav": "[← Voltar à descrição do jogo](../../README.md) ｜ [← sub-biblioteca hsr-glossary](../README.md)",
        "intro": "Este diretório contém a base de terminologia de Honkai: Star Rail com **`{lang}` ({lang_label}) como idioma de destino**: **{ncat}** CSV de categorias e **{rows:,}** linhas de correspondência. A coluna `tgt_lng` é sempre `{lang}` e a coluna `source` traz a localização oficial dos restantes idiomas.",
        "files_head": "Ficheiros",
        "files_intro": "O diretório é **plano**: os {ncat} CSV de categorias estão diretamente aqui.",
        "cols": ("Ficheiro", "Categoria", "Linhas neste idioma"),
        "notes_head": "Notas",
        "bullets": [
            "Os textos vêm da localização do cliente (TextMap / ExcelOutput), alinhados pela mesma chave de texto — não é tradução de segunda mão.",
            "Se o idioma de destino não tiver texto para uma chave, nenhuma linha é criada e nada é traduzido automaticamente.",
            "A mesma chave pode ter várias formas oficiais conforme o contexto; todas são mantidas.",
            "Gerado por `../../tools/build_hsr_glossary.py`, totalmente reproduzível.",
        ],
    },
    "id-ID": {
        "title": "Basis Terminologi Honkai: Star Rail — {lang_label} (`{lang}`)",
        "nav": "[← Kembali ke penjelasan game](../../README.md) ｜ [← sub-pustaka hsr-glossary](../README.md)",
        "intro": "Direktori ini berisi basis terminologi Honkai: Star Rail dengan **`{lang}` ({lang_label}) sebagai bahasa target**: **{ncat}** CSV kategori dan **{rows:,}** baris padanan. Kolom `tgt_lng` selalu `{lang}` dan kolom `source` memuat lokalisasi resmi bahasa lain.",
        "files_head": "Berkas",
        "files_intro": "Direktori ini **datar**: {ncat} CSV kategori berada langsung di sini.",
        "cols": ("Berkas", "Kategori", "Baris pada bahasa ini"),
        "notes_head": "Catatan",
        "bullets": [
            "Teks terjemahan berasal dari lokalisasi klien (TextMap / ExcelOutput), diselaraskan dengan kunci teks yang sama — bukan terjemahan ulang.",
            "Jika bahasa target tidak memiliki teks untuk sebuah kunci, baris tidak dibuat dan tidak diisi dengan terjemahan mesin.",
            "Satu kunci teks bisa punya beberapa padanan resmi tergantung konteks; semuanya dipertahankan.",
            "Dibuat oleh `../../tools/build_hsr_glossary.py`, dapat direproduksi.",
        ],
    },
    "th-TH": {
        "title": "ฐานข้อมูลคำศัพท์ Honkai: Star Rail — {lang_label} (`{lang}`)",
        "nav": "[← กลับไปยังคำอธิบายเกม](../../README.md) ｜ [← คำอธิบาย hsr-glossary](../README.md)",
        "intro": "ไดเรกทอรีนี้เป็นฐานข้อมูลคำศัพท์ Honkai: Star Rail ที่**ใช้ `{lang}` ({lang_label}) เป็นภาษาปลายทาง** มีไฟล์ CSV **{ncat}** หมวดหมู่ และ **{rows:,}** แถวเทียบเคียง คอลัมน์ `tgt_lng` เป็น `{lang}` เสมอ ส่วนคอลัมน์ `source` เก็บข้อความโลคัลไลซ์ทางการของภาษาอื่น",
        "files_head": "ไฟล์",
        "files_intro": "ไดเรกทอรีนี้เป็น**โครงสร้างแบน**: ไฟล์ CSV {ncat} หมวดหมู่วางอยู่ที่นี่โดยตรง",
        "cols": ("ไฟล์", "หมวดหมู่", "จำนวนแถวในภาษานี้"),
        "notes_head": "หมายเหตุ",
        "bullets": [
            "คำแปลมาจากข้อความโลคัลไลซ์ของตัวเกม (TextMap / ExcelOutput) จับคู่ด้วยคีย์ข้อความเดียวกัน ไม่ใช่การแปลซ้ำ",
            "หากภาษาปลายทางไม่มีข้อความสำหรับคีย์นั้น จะไม่สร้างแถวและไม่เติมด้วยการแปลด้วยเครื่อง",
            "คีย์เดียวกันอาจมีคำแปลทางการได้หลายแบบตามบริบท ทั้งหมดจะถูกเก็บไว้",
            "สร้างด้วย `../../tools/build_hsr_glossary.py` ทำซ้ำได้",
        ],
    },
    "vi-VN": {
        "title": "Cơ sở thuật ngữ Honkai: Star Rail — {lang_label} (`{lang}`)",
        "nav": "[← Quay lại phần giới thiệu game](../../README.md) ｜ [← thư mục con hsr-glossary](../README.md)",
        "intro": "Thư mục này chứa cơ sở thuật ngữ Honkai: Star Rail với **`{lang}` ({lang_label}) là ngôn ngữ đích**: **{ncat}** tệp CSV theo hạng mục và **{rows:,}** dòng đối chiếu. Cột `tgt_lng` luôn là `{lang}`, cột `source` chứa bản địa hóa chính thức của các ngôn ngữ khác.",
        "files_head": "Tệp",
        "files_intro": "Thư mục có **cấu trúc phẳng**: {ncat} tệp CSV hạng mục nằm trực tiếp tại đây.",
        "cols": ("Tệp", "Hạng mục", "Số dòng của ngôn ngữ này"),
        "notes_head": "Ghi chú",
        "bullets": [
            "Bản dịch lấy từ bản địa hóa của client (TextMap / ExcelOutput), căn theo cùng một khóa văn bản — không phải dịch lại.",
            "Nếu ngôn ngữ đích thiếu văn bản cho một khóa, sẽ không tạo dòng nào và không dùng dịch máy để bù.",
            "Một khóa văn bản có thể có nhiều cách diễn đạt chính thức tùy ngữ cảnh; tất cả đều được giữ lại.",
            "Được tạo bởi `../../tools/build_hsr_glossary.py`, có thể tái lập.",
        ],
    },
}


def main() -> int:
    stats = load(TOOLS / "_counts.json", {})
    validation = load(TOOLS / "_validation.json", {})
    history = load(GLOSSARY / "historical" / "_history_counts.json", {})
    curated = load(GLOSSARY / "curated" / "_curated_counts.json", {})

    counts = stats["counts"]
    concepts = stats["concept_counts"]
    totals = stats["totals"]
    grand = stats["grand_total"]
    conflicts = stats["conflicts"]
    unique_concepts = stats["unique_concepts"]
    history_rows = history.get("rows", 0)
    curated_rows = curated.get("rows", 0)

    lang_rows = "".join(
        f"| `{lang}` | {LANG_LABELS[lang]} | {totals[lang]:,} |\n" for lang in LANG_ORDER
    )
    lang_rows_en = "".join(
        f"| `{lang}` | {LANG_LABELS[lang]} | {totals[lang]:,} |\n" for lang in LANG_ORDER
    )
    category_rows = "".join(
        f"| `{cat}` | {CATEGORY_LABELS[cat][0]} | {CATEGORY_LABELS[cat][1]} | "
        f"{concepts[cat]:,} | {sum(counts[cat][lang] for lang in LANG_ORDER):,} |\n"
        for cat in CATEGORIES
    )
    file_list = "".join(
        f"- `{cat}.csv` — {CATEGORY_LABELS[cat][0]} / {CATEGORY_LABELS[cat][1]}\n" for cat in CATEGORIES
    )

    glossary_readme = f"""# 崩坏：星穹铁道（Honkai: Star Rail）多语言术语库

本目录按目标语言存放《崩坏：星穹铁道》（Honkai: Star Rail / HSR）术语表。
每个 CSV 文件严格只有三列：`source`、`target`、`tgt_lng`。

- 记录总数：**{grand:,}**
- 去重术语键（concept）：**{unique_concepts:,}**
- 目标语言：**{len(LANG_ORDER)}**
- 分类：**{len(CATEGORIES)}**
- 客户端数据版本：`{stats.get('game_version', '')}`

`source` 是同一个游戏文本键在其它语言的官方本地化文本，`target` 是本目录语言的官方本地化文本，
两者通过 TextMap Hash / 实体 ID 对齐，不使用机器翻译。

文件使用仓库统一的 CSV 形式（`source,target,tgt_lng` 三列，UTF-8 含 BOM、CRLF）。
如需制表符分隔的同内容文件，可用 `python ../tools/build_hsr_glossary.py --format tsv` 生成
同名 `.tsv` 文件（列结构完全一致，仅分隔符不同）。

重新生成与校验：

```bash
python ../tools/build_hsr_glossary.py
python ../tools/build_hsr_history.py
python ../tools/build_hsr_curated.py
python ../tools/validate_hsr_glossary.py
python ../tools/make_hsr_docs.py
```

## 各语言规模

| 目标语言 | 语言 | 记录数 |
| --- | --- | ---: |
{lang_rows}
## 分类规模

| 分类 | 中文名 | English | 独立术语键 | 全语言记录数 |
| --- | --- | --- | ---: | ---: |
{category_rows}
## 其它目录

- `historical/` — 与旧版本客户端（2.3.0 / 4.0）比对得到的历史译名变化。
- `curated/` — 少量人工核对条目（如开拓者/主角），全部在客户端文本中验证存在。

## 质量校验

最近一次校验结果（`../tools/_validation.json`）：

| 检查项 | 结果 |
| --- | ---: |
| 空 source / 空 target | {validation.get('issues', {}).get('empty_source', 0)} / {validation.get('issues', {}).get('empty_target', 0)} |
| 语言代码错误 | {validation.get('issues', {}).get('bad_language', 0)} |
| 重复记录 | {validation.get('issues', {}).get('duplicate_row', 0)} |
| HTML 标签 | {validation.get('issues', {}).get('html_tag', 0)} |
| 开发变量 | {validation.get('issues', {}).get('dev_variable', 0)} |
| Hash / 内部 ID | {validation.get('issues', {}).get('hash_like', 0)} / {validation.get('issues', {}).get('internal_id', 0)} |
| N/A 等占位符 | {validation.get('issues', {}).get('na_value', 0)} |
| 目标文本未出现在客户端文本中 | {validation.get('issues', {}).get('not_in_client_data', 0)} |
| 机器翻译记录 | {validation.get('issues', {}).get('machine_translation', 0)} |
"""

    (GLOSSARY / "README.md").write_text(glossary_readme, encoding="utf-8")

    for lang in LANG_ORDER:
        rows = totals[lang]
        pack = LANG_PACK[lang]
        others = "、".join(f"`{other}`" for other in LANG_ORDER if other != lang)
        use_zh_labels = lang in ("zh-CN", "zh-TW")
        per_cat = "\n".join(
            f"| `{cat}.csv` | {CATEGORY_LABELS[cat][0] if use_zh_labels else CATEGORY_LABELS[cat][1]} | "
            f"{counts[cat][lang]:,} |"
            for cat in CATEGORIES
        )
        bullet_text = "".join(f"- {b}\n" for b in pack["bullets"])
        col_file, col_cat, col_rows = pack["cols"]
        text = f"""# {pack['title'].format(lang_label=LANG_LABELS[lang], lang=lang)}

{pack['nav']}

{pack['intro'].format(lang=lang, lang_label=LANG_LABELS[lang], ncat=len(CATEGORIES), rows=rows, others=others)}

## {pack['files_head']}

{pack['files_intro'].format(ncat=len(CATEGORIES))}

| {col_file} | {col_cat} | {col_rows} |
| --- | --- | ---: |
{per_cat}

## {pack['notes_head']}

{bullet_text}"""
        (GLOSSARY / lang / "README.md").write_text(text, encoding="utf-8")

        zh_pack = LANG_PACK["zh-CN"]
        zh_per_cat = "\n".join(
            f"| `{cat}.csv` | {CATEGORY_LABELS[cat][0]} | {counts[cat][lang]:,} |" for cat in CATEGORIES
        )
        zh_bullets = "".join(f"- {b}\n" for b in zh_pack["bullets"])
        zh_text = f"""# {zh_pack['title'].format(lang_label=LANG_LABELS[lang], lang=lang)}

{zh_pack['nav']}

{zh_pack['intro'].format(lang=lang, lang_label=LANG_LABELS[lang], ncat=len(CATEGORIES), rows=rows, others=others)}

## {zh_pack['files_head']}

{zh_pack['files_intro'].format(ncat=len(CATEGORIES))}

| {zh_pack['cols'][0]} | {zh_pack['cols'][1]} | {zh_pack['cols'][2]} |
| --- | --- | ---: |
{zh_per_cat}

## {zh_pack['notes_head']}

{zh_bullets}"""
        (GLOSSARY / lang / "README_zh-CN.md").write_text(zh_text, encoding="utf-8")
        print("wrote", GLOSSARY / lang / "README.md", "+ README_zh-CN.md")

    metadata = ROOT / "Metadata"
    metadata.mkdir(exist_ok=True)
    statistics = f"""# 《崩坏：星穹铁道》术语库统计

生成日期：{stats.get('generated', '')}
客户端数据版本：`{stats.get('game_version', '')}`

## 总量

| 指标 | 数值 |
| --- | ---: |
| 总记录数（所有语言 `source,target,tgt_lng` 行） | {grand:,} |
| 去重术语键（concept）总数 | {unique_concepts:,} |
| 目标语言数 | {len(LANG_ORDER)} |
| 分类数 | {len(CATEGORIES)} |
| 已确认条目（目标文本可在客户端 TextMap 中逐字验证） | {validation.get('rows', grand):,} |
| 未确认条目（未生成 / 未猜测） | 0 |
| 机器翻译条目 | 0 |
| 历史词条（旧版本译名变化） | {history_rows:,} |
| 人工核对条目（curated） | {curated_rows:,} |
| 多译名冲突组（同一 source 在同一语言同一分类下对应多个 target） | {conflicts:,} |

## 各语言数量

| 目标语言 | 语言 | 记录数 |
| --- | --- | ---: |
{lang_rows}
## 各分类数量

| 分类 | 中文名 | English | 独立术语键 | 全语言记录数 |
| --- | --- | --- | ---: | ---: |
{category_rows}
## 历史词条来源

| 对比基线 | 版本 | 检出差异记录数 |
| --- | --- | ---: |
| StarRailStaticAPI | 2.3.0 | {history.get('sources', {}).get('StarRailStaticAPI 2.3.0', {}).get('total', 0):,} |
| HSR-Mapping-DATA | 4.0 | {history.get('sources', {}).get('HSR-Mapping-DATA 4.0', {}).get('total', 0):,} |
| 去重后 | — | {history_rows:,} |

## 第二轮抽样核对

| 分类 | 抽样条数 | 在 StarRailRes 独立索引中命中 |
| --- | ---: | ---: |
""" + "".join(
        f"| `{cat}` | {info['sampled']:,} | {info['verified_against_starrailres']:,} |\n"
        for cat, info in validation.get("cross_check", {}).items()
    ) + """
> StarRailRes 与客户端 TextMap 属于同一份数据的两种整理方式，用于交叉验证名称与 ID 的对应关系；
> 没有 StarRailRes 对应文件的门类（任务、活动、剧情、系统、UI、书籍等）以客户端 TextMap 逐字验证为准。
"""
    (metadata / "statistics.md").write_text(statistics, encoding="utf-8")
    print("wrote", metadata / "statistics.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
