# -*- coding: utf-8 -*-
"""Curated naval / military / game terminology for the Azur Lane glossary.
Each entry: (src_lng, source, target, category)
"""

TERMS = [
    # ---------------- hull / ship types ----------------
    ('en', 'Destroyer', '驱逐舰', 'hull_type'),
    ('en', 'DD', '驱逐舰', 'hull_type'),
    ('en', 'Light Cruiser', '轻巡洋舰', 'hull_type'),
    ('en', 'CL', '轻巡洋舰', 'hull_type'),
    ('en', 'Heavy Cruiser', '重巡洋舰', 'hull_type'),
    ('en', 'CA', '重巡洋舰', 'hull_type'),
    ('en', 'Large Cruiser', '超巡洋舰', 'hull_type'),
    ('en', 'CB', '超巡洋舰', 'hull_type'),
    ('en', 'Battlecruiser', '战列巡洋舰', 'hull_type'),
    ('en', 'BC', '战列巡洋舰', 'hull_type'),
    ('en', 'Battleship', '战列舰', 'hull_type'),
    ('en', 'BB', '战列舰', 'hull_type'),
    ('en', 'Aviation Battleship', '航空战列舰', 'hull_type'),
    ('en', 'BBV', '航空战列舰', 'hull_type'),
    ('en', 'Aviation Cruiser', '航空巡洋舰', 'hull_type'),
    ('en', 'Torpedo Cruiser', '鱼雷巡洋舰', 'hull_type'),
    ('en', 'Aircraft Carrier', '航空母舰', 'hull_type'),
    ('en', 'CV', '航空母舰', 'hull_type'),
    ('en', 'Light Carrier', '轻型航空母舰', 'hull_type'),
    ('en', 'CVL', '轻型航空母舰', 'hull_type'),
    ('en', 'Escort Carrier', '护航航空母舰', 'hull_type'),
    ('en', 'CVE', '护航航空母舰', 'hull_type'),
    ('en', 'Submarine', '潜艇', 'hull_type'),
    ('en', 'SS', '潜艇', 'hull_type'),
    ('en', 'Aviation Submarine', '潜水航母', 'hull_type'),
    ('en', 'SSV', '潜水航母', 'hull_type'),
    ('en', 'Monitor', '浅水重炮舰', 'hull_type'),
    ('en', 'BM', '浅水重炮舰', 'hull_type'),
    ('en', 'Repair Ship', '维修舰', 'hull_type'),
    ('en', 'AR', '维修舰', 'hull_type'),
    ('en', 'Munition Ship', '运输舰', 'hull_type'),
    ('en', 'DDG', '导弹驱逐舰', 'hull_type'),
    ('en', 'Sailing Frigate', '风帆舰', 'hull_type'),
    ('en', 'Destroyer Escort', '护航驱逐舰', 'hull_type'),
    ('en', 'DE', '护航驱逐舰', 'hull_type'),
    ('en', 'Minesweeper', '扫雷舰', 'hull_type'),
    ('en', 'Minelayer', '布雷舰', 'hull_type'),
    ('en', 'Submarine Tender', '潜艇母舰', 'hull_type'),
    ('en', 'Seaplane Tender', '水上机母舰', 'hull_type'),
    ('en', 'Landing Ship', '登陆舰', 'hull_type'),
    ('en', 'Frigate', '护卫舰', 'hull_type'),
    ('en', 'Corvette', '轻型护卫舰', 'hull_type'),
    ('en', 'Gunboat', '炮舰', 'hull_type'),
    ('en', 'Torpedo Boat', '鱼雷艇', 'hull_type'),
    ('ja', '駆逐艦', '驱逐舰', 'hull_type'),
    ('ja', '軽巡洋艦', '轻巡洋舰', 'hull_type'),
    ('ja', '重巡洋艦', '重巡洋舰', 'hull_type'),
    ('ja', '超甲型巡洋艦', '超巡洋舰', 'hull_type'),
    ('ja', '巡洋戦艦', '战列巡洋舰', 'hull_type'),
    ('ja', '戦艦', '战列舰', 'hull_type'),
    ('ja', '航空戦艦', '航空战列舰', 'hull_type'),
    ('ja', '航空巡洋艦', '航空巡洋舰', 'hull_type'),
    ('ja', '重雷装巡洋艦', '鱼雷巡洋舰', 'hull_type'),
    ('ja', '航空母艦', '航空母舰', 'hull_type'),
    ('ja', '正規空母', '正规航空母舰', 'hull_type'),
    ('ja', '軽空母', '轻型航空母舰', 'hull_type'),
    ('ja', '護衛空母', '护航航空母舰', 'hull_type'),
    ('ja', '潜水艦', '潜艇', 'hull_type'),
    ('ja', '潜水空母', '潜水航母', 'hull_type'),
    ('ja', '水上機母艦', '水上机母舰', 'hull_type'),
    ('ja', '工作艦', '维修舰', 'hull_type'),
    ('ja', '輸送艦', '运输舰', 'hull_type'),
    ('ja', '砲艦', '炮舰', 'hull_type'),
    ('ja', '水雷艇', '鱼雷艇', 'hull_type'),
    ('ja', '掃海艇', '扫雷艇', 'hull_type'),
    ('ja', '帆船', '风帆舰', 'hull_type'),

    # ---------------- navy / prefix ----------------
    ('en', 'USS', '美国海军（白鹰）', 'navy_prefix'),
    ('en', 'HMS', '英国皇家海军（皇家）', 'navy_prefix'),
    ('en', 'IJN', '旧日本海军（重樱）', 'navy_prefix'),
    ('en', 'KMS', '德国海军（铁血）', 'navy_prefix'),
    ('en', 'SMS', '德意志帝国海军', 'navy_prefix'),
    ('en', 'SN', '苏联海军（北方联合）', 'navy_prefix'),
    ('en', 'RN', '意大利皇家海军（撒丁帝国）', 'navy_prefix'),
    ('en', 'FFNF', '自由法国海军（自由鸢尾）', 'navy_prefix'),
    ('en', 'MNF', '法国海军（维希教廷）', 'navy_prefix'),
    ('en', 'HNLMS', '荷兰皇家海军（郁金王国）', 'navy_prefix'),
    ('en', 'MOT', '飓风船团', 'navy_prefix'),
    ('en', 'UNIV', '通用型', 'navy_prefix'),
    ('en', 'Eagle Union', '白鹰', 'navy_prefix'),
    ('en', 'Royal Navy', '皇家', 'navy_prefix'),
    ('en', 'Sakura Empire', '重樱', 'navy_prefix'),
    ('en', 'Iron Blood', '铁血', 'navy_prefix'),
    ('en', 'Dragon Empery', '东煌', 'navy_prefix'),
    ('en', 'Sardegna Empire', '撒丁帝国', 'navy_prefix'),
    ('en', 'Northern Parliament', '北方联合', 'navy_prefix'),
    ('en', 'Iris Libre', '自由鸢尾', 'navy_prefix'),
    ('en', 'Vichya Dominion', '维希教廷', 'navy_prefix'),
    ('en', 'Kingdom of Tulipa', '郁金王国', 'navy_prefix'),
    ('en', 'Tempesta', '飓风船团', 'navy_prefix'),
    ('en', 'Siren', '塞壬', 'navy_prefix'),
    ('en', 'META', 'META', 'navy_prefix'),
    ('ja', '連合艦隊', '联合舰队', 'navy_prefix'),
    ('ja', '白鷹', '白鹰', 'navy_prefix'),
    ('ja', 'ロイヤル', '皇家', 'navy_prefix'),
    ('ja', '重桜', '重樱', 'navy_prefix'),
    ('ja', '鉄血', '铁血', 'navy_prefix'),
    ('ja', '東煌', '东煌', 'navy_prefix'),
    ('ja', 'サディア帝国', '撒丁帝国', 'navy_prefix'),
    ('ja', '北方連合', '北方联合', 'navy_prefix'),
    ('ja', 'アイリス', '自由鸢尾', 'navy_prefix'),
    ('ja', 'ヴィシア', '维希教廷', 'navy_prefix'),
    ('ja', 'セイレーン', '塞壬', 'navy_prefix'),

    # ---------------- ranks ----------------
    ('en', 'Fleet Admiral', '海军元帅', 'rank'),
    ('en', 'Admiral', '海军上将', 'rank'),
    ('en', 'Vice Admiral', '海军中将', 'rank'),
    ('en', 'Rear Admiral', '海军少将', 'rank'),
    ('en', 'Commodore', '海军准将', 'rank'),
    ('en', 'Captain', '海军上校', 'rank'),
    ('en', 'Commander', '海军中校', 'rank'),
    ('en', 'Lieutenant Commander', '海军少校', 'rank'),
    ('en', 'Lieutenant', '海军上尉', 'rank'),
    ('en', 'Lieutenant Junior Grade', '海军中尉', 'rank'),
    ('en', 'Ensign', '海军少尉', 'rank'),
    ('en', 'Commander-in-Chief', '总司令', 'rank'),
    ('en', 'Chief of Staff', '参谋长', 'rank'),
    ('ja', '元帥', '元帅', 'rank'),
    ('ja', '大将', '大将', 'rank'),
    ('ja', '中将', '中将', 'rank'),
    ('ja', '少将', '少将', 'rank'),
    ('ja', '大佐', '大佐（上校）', 'rank'),
    ('ja', '中佐', '中佐（中校）', 'rank'),
    ('ja', '少佐', '少佐（少校）', 'rank'),
    ('ja', '大尉', '大尉（上尉）', 'rank'),
    ('ja', '中尉', '中尉', 'rank'),
    ('ja', '少尉', '少尉', 'rank'),
    ('ja', '参謀長', '参谋长', 'rank'),
    ('ja', '司令長官', '司令长官', 'rank'),

    # ---------------- naval terminology ----------------
    ('en', 'flagship', '旗舰', 'naval_term'),
    ('en', 'sister ship', '姐妹舰', 'naval_term'),
    ('en', 'lead ship', '首舰', 'naval_term'),
    ('en', 'name ship', '同名舰', 'naval_term'),
    ('en', 'fleet', '舰队', 'naval_term'),
    ('en', 'vanguard', '先锋舰队（前排）', 'naval_term'),
    ('en', 'main fleet', '主力舰队（后排）', 'naval_term'),
    ('en', 'task force', '特混舰队', 'naval_term'),
    ('en', 'squadron', '战队', 'naval_term'),
    ('en', 'flotilla', '水雷战队', 'naval_term'),
    ('en', 'sortie', '出击', 'naval_term'),
    ('en', 'commissioned', '服役', 'naval_term'),
    ('en', 'launched', '下水', 'naval_term'),
    ('en', 'sunk', '击沉', 'naval_term'),
    ('en', 'scuttled', '自沉', 'naval_term'),
    ('en', 'displacement', '排水量', 'naval_term'),
    ('en', 'standard displacement', '标准排水量', 'naval_term'),
    ('en', 'full load displacement', '满载排水量', 'naval_term'),
    ('en', 'tonnage', '吨位', 'naval_term'),
    ('en', 'knot', '节', 'naval_term'),
    ('en', 'speed', '航速', 'naval_term'),
    ('en', 'cruising range', '续航距离', 'naval_term'),
    ('en', 'crew', '舰员', 'naval_term'),
    ('en', 'armament', '武装', 'naval_term'),
    ('en', 'main gun', '主炮', 'naval_term'),
    ('en', 'secondary gun', '副炮', 'naval_term'),
    ('en', 'anti-aircraft gun', '防空炮', 'naval_term'),
    ('en', 'machine gun', '机枪', 'naval_term'),
    ('en', 'torpedo', '鱼雷', 'naval_term'),
    ('en', 'torpedo tube', '鱼雷发射管', 'naval_term'),
    ('en', 'depth charge', '深水炸弹', 'naval_term'),
    ('en', 'sonar', '声呐', 'naval_term'),
    ('en', 'radar', '雷达', 'naval_term'),
    ('en', 'armor', '装甲', 'naval_term'),
    ('en', 'belt armor', '舷侧装甲', 'naval_term'),
    ('en', 'deck armor', '甲板装甲', 'naval_term'),
    ('en', 'turret', '炮塔', 'naval_term'),
    ('en', 'hull', '船体', 'naval_term'),
    ('en', 'bow', '舰首', 'naval_term'),
    ('en', 'stern', '舰尾', 'naval_term'),
    ('en', 'bridge', '舰桥', 'naval_term'),
    ('en', 'funnel', '烟囱', 'naval_term'),
    ('en', 'mast', '桅杆', 'naval_term'),
    ('en', 'flight deck', '飞行甲板', 'naval_term'),
    ('en', 'catapult', '弹射器', 'naval_term'),
    ('en', 'carrier-based aircraft', '舰载机', 'naval_term'),
    ('en', 'fighter', '战斗机', 'naval_term'),
    ('en', 'dive bomber', '俯冲轰炸机', 'naval_term'),
    ('en', 'torpedo bomber', '鱼雷机', 'naval_term'),
    ('en', 'reconnaissance aircraft', '侦察机', 'naval_term'),
    ('en', 'seaplane', '水上飞机', 'naval_term'),
    ('en', 'flying boat', '飞行艇', 'naval_term'),
    ('en', 'escort', '护航', 'naval_term'),
    ('en', 'convoy', '运输船队', 'naval_term'),
    ('en', 'patrol', '巡逻', 'naval_term'),
    ('en', 'blockade', '封锁', 'naval_term'),
    ('en', 'naval bombardment', '舰炮射击', 'naval_term'),
    ('en', 'reconnaissance', '侦察', 'naval_term'),
    ('en', 'searchlight', '探照灯', 'naval_term'),
    ('en', 'anti-submarine warfare', '反潜作战', 'naval_term'),
    ('en', 'refit', '改装', 'naval_term'),
    ('en', 'blueprint', '图纸', 'naval_term'),
    ('en', 'dry dock', '干船坞', 'naval_term'),
    ('en', 'shipyard', '造船厂', 'naval_term'),
    ('en', 'dry cargo ship', '干货船', 'naval_term'),
    ('en', 'oiler', '油船', 'naval_term'),
    ('en', 'ammunition ship', '弹药船', 'naval_term'),
    ('ja', '旗艦', '旗舰', 'naval_term'),
    ('ja', '姉妹艦', '姐妹舰', 'naval_term'),
    ('ja', 'ネームシップ', '首舰', 'naval_term'),
    ('ja', '艦隊', '舰队', 'naval_term'),
    ('ja', '前衛', '先锋舰队（前排）', 'naval_term'),
    ('ja', '主力艦隊', '主力舰队（后排）', 'naval_term'),
    ('ja', '機動部隊', '机动部队', 'naval_term'),
    ('ja', '戦隊', '战队', 'naval_term'),
    ('ja', '水雷戦隊', '水雷战队', 'naval_term'),
    ('ja', '出撃', '出击', 'naval_term'),
    ('ja', '就役', '服役', 'naval_term'),
    ('ja', '進水', '下水', 'naval_term'),
    ('ja', '撃沈', '击沉', 'naval_term'),
    ('ja', '自沈', '自沉', 'naval_term'),
    ('ja', '排水量', '排水量', 'naval_term'),
    ('ja', '基準排水量', '标准排水量', 'naval_term'),
    ('ja', '満載排水量', '满载排水量', 'naval_term'),
    ('ja', 'ノット', '节', 'naval_term'),
    ('ja', '速力', '航速', 'naval_term'),
    ('ja', '航続距離', '续航距离', 'naval_term'),
    ('ja', '乗員', '舰员', 'naval_term'),
    ('ja', '兵装', '武装', 'naval_term'),
    ('ja', '主砲', '主炮', 'naval_term'),
    ('ja', '副砲', '副炮', 'naval_term'),
    ('ja', '高角砲', '防空炮', 'naval_term'),
    ('ja', '機銃', '机枪', 'naval_term'),
    ('ja', '魚雷', '鱼雷', 'naval_term'),
    ('ja', '発射管', '鱼雷发射管', 'naval_term'),
    ('ja', '爆雷', '深水炸弹', 'naval_term'),
    ('ja', 'ソナー', '声呐', 'naval_term'),
    ('ja', 'レーダー', '雷达', 'naval_term'),
    ('ja', '装甲', '装甲', 'naval_term'),
    ('ja', '砲塔', '炮塔', 'naval_term'),
    ('ja', '船体', '船体', 'naval_term'),
    ('ja', '艦首', '舰首', 'naval_term'),
    ('ja', '艦尾', '舰尾', 'naval_term'),
    ('ja', '艦橋', '舰桥', 'naval_term'),
    ('ja', '煙突', '烟囱', 'naval_term'),
    ('ja', 'マスト', '桅杆', 'naval_term'),
    ('ja', '飛行甲板', '飞行甲板', 'naval_term'),
    ('ja', 'カタパルト', '弹射器', 'naval_term'),
    ('ja', '艦載機', '舰载机', 'naval_term'),
    ('ja', '戦闘機', '战斗机', 'naval_term'),
    ('ja', '急降下爆撃機', '俯冲轰炸机', 'naval_term'),
    ('ja', '雷撃機', '鱼雷机', 'naval_term'),
    ('ja', '偵察機', '侦察机', 'naval_term'),
    ('ja', '水上機', '水上飞机', 'naval_term'),
    ('ja', '護衛', '护航', 'naval_term'),
    ('ja', '船団', '运输船队', 'naval_term'),
    ('ja', '哨戒', '巡逻', 'naval_term'),
    ('ja', '封鎖', '封锁', 'naval_term'),
    ('ja', '艦砲射撃', '舰炮射击', 'naval_term'),
    ('ja', '偵察', '侦察', 'naval_term'),
    ('ja', '探照灯', '探照灯', 'naval_term'),
    ('ja', '対潜', '反潜', 'naval_term'),
    ('ja', '改装', '改装', 'naval_term'),
    ('ja', '図面', '图纸', 'naval_term'),
    ('ja', '乾ドック', '干船坞', 'naval_term'),
    ('ja', '造船所', '造船厂', 'naval_term'),
    ('ja', '級', '级', 'naval_term'),
    ('ja', '型', '型', 'naval_term'),
    ('ja', 'ドック', '船坞', 'naval_term'),

    # ---------------- in-game terminology ----------------
    ('en', 'Retrofit', '改造', 'game_term'),
    ('en', 'Blueprint', '图纸', 'game_term'),
    ('en', 'Limit Break', '突破', 'game_term'),
    ('en', 'Oath', '誓约', 'game_term'),
    ('en', 'Oath Ring', '誓约之戒', 'game_term'),
    ('en', 'Secretary Ship', '秘书舰', 'game_term'),
    ('en', 'Dorm', '后宅', 'game_term'),
    ('en', 'Commission', '委托', 'game_term'),
    ('en', 'Exercise', '演习', 'game_term'),
    ('en', 'Sortie', '出击', 'game_term'),
    ('en', 'Fleet', '舰队', 'game_term'),
    ('en', 'Equipment', '装备', 'game_term'),
    ('en', 'Auxiliary Equipment', '设备', 'game_term'),
    ('en', 'Skill', '技能', 'game_term'),
    ('en', 'Barrage', '弹幕', 'game_term'),
    ('en', 'Oil', '石油', 'game_term'),
    ('en', 'Coin', '物资', 'game_term'),
    ('en', 'Diamond', '钻石', 'game_term'),
    ('en', 'Cognition', '心智', 'game_term'),
    ('en', 'Cognitive Chip', '心智单元', 'game_term'),
    ('en', 'PR Ship', '决战方案', 'game_term'),
    ('en', 'Research Ship', '科研船', 'game_term'),
    ('en', 'Specialized Bulin', '特装型布里', 'game_term'),
    ('en', 'Universal Bulin', '泛用型布里', 'game_term'),
    ('en', 'μ Equipment', 'μ兵装', 'game_term'),
    ('en', 'META', 'META', 'game_term'),
    ('ja', '改造', '改造', 'game_term'),
    ('ja', '図面', '图纸', 'game_term'),
    ('ja', '限界突破', '突破', 'game_term'),
    ('ja', '誓約', '誓约', 'game_term'),
    ('ja', '誓約の指輪', '誓约之戒', 'game_term'),
    ('ja', '秘書艦', '秘书舰', 'game_term'),
    ('ja', '寮', '后宅', 'game_term'),
    ('ja', '委託', '委托', 'game_term'),
    ('ja', '演習', '演习', 'game_term'),
    ('ja', '出撃', '出击', 'game_term'),
    ('ja', '装備', '装备', 'game_term'),
    ('ja', 'スキル', '技能', 'game_term'),
    ('ja', '弾幕', '弹幕', 'game_term'),
    ('ja', '石油', '石油', 'game_term'),
    ('ja', '資材', '物资', 'game_term'),
    ('ja', 'ダイヤ', '钻石', 'game_term'),
    ('ja', 'μ兵装', 'μ兵装', 'game_term'),
    ('ja', 'ブリ', '布里', 'game_term'),
    ('ja', '汎用型ブリ', '泛用型布里', 'game_term'),
    ('ja', '試作型ブリ', '试作型布里', 'game_term'),
]

CATEGORY_ZH = {
    'hull_type': '舰种',
    'navy_prefix': '阵营/舰名前缀',
    'rank': '军衔',
    'naval_term': '航海/军事术语',
    'game_term': '游戏术语',
}

# ---------------- Korean ----------------
# One Korean form per concept above.  Ship types, factions and in-game UI words were
# taken from the KR client's own tables (ship_data_by_type, fleet_tech_group,
# world_port_data, medal_template, emoji_template, enemy_data_statistics, ...);
# the remaining naval / rank words are the standard Korean equivalents.
KO_TERMS = [
    # game terms
    ('设备', '보조장비'),
    ('弹幕', '탄막'),
    ('图纸', '도면'),
    ('心智', '성정'),
    ('心智单元', '성정 유닛'),
    ('物资', '자재'),
    ('委托', '위탁'),
    ('钻石', '다이아'),
    ('后宅', '숙소'),
    ('装备', '장비'),
    ('演习', '연습전'),
    ('舰队', '함대'),
    ('突破', '한계돌파'),
    ('誓约', '서약'),
    ('誓约之戒', '서약의 반지'),
    ('石油', '석유'),
    ('决战方案', '결전 방안'),
    ('科研船', '연구함'),
    ('改造', '개조'),
    ('秘书舰', '비서함'),
    ('技能', '스킬'),
    ('出击', '출격'),
    ('特装型布里', '특장형 부린'),
    ('泛用型布里', '범용형 부린'),
    ('μ兵装', 'μ장비'),
    ('布里', '부린'),
    ('试作型布里', '시제형 부린'),
    # hull types
    ('航空母舰', '항공모함'),
    ('维修舰', '공작함'),
    ('航空战列舰', '항공전함'),
    ('航空巡洋舰', '항공순양함'),
    ('潜水航母', '잠수항모'),
    ('战列巡洋舰', '순양전함'),
    ('战列舰', '전함'),
    ('浅水重炮舰', '모니터함'),
    ('重巡洋舰', '중순양함'),
    ('超巡洋舰', '대형순양함'),
    ('轻巡洋舰', '경순양함'),
    ('轻型护卫舰', '초계함'),
    ('护航航空母舰', '호위항공모함'),
    ('轻型航空母舰', '경항공모함'),
    ('驱逐舰', '구축함'),
    ('导弹驱逐舰', '미사일 구축함'),
    ('护航驱逐舰', '호위구축함'),
    ('护卫舰', '호위함'),
    ('炮舰', '포함'),
    ('登陆舰', '상륙함'),
    ('布雷舰', '기뢰부설함'),
    ('扫雷舰', '소해함'),
    ('运输舰', '수송함'),
    ('风帆舰', '범선'),
    ('水上机母舰', '수상기모함'),
    ('潜艇', '잠수함'),
    ('潜艇母舰', '잠수모함'),
    ('鱼雷艇', '어뢰정'),
    ('鱼雷巡洋舰', '어뢰순양함'),
    ('扫雷艇', '소해정'),
    ('正规航空母舰', '정규항공모함'),
    # naval / military terms
    ('弹药船', '탄약운반함'),
    ('防空炮', '대공포'),
    ('反潜作战', '대잠전'),
    ('武装', '무장'),
    ('装甲', '장갑'),
    ('舷侧装甲', '현측장갑'),
    ('封锁', '봉쇄'),
    ('舰首', '함수'),
    ('舰桥', '함교'),
    ('舰载机', '함재기'),
    ('弹射器', '캐터펄트'),
    ('服役', '취역'),
    ('运输船队', '수송선단'),
    ('舰员', '승조원'),
    ('续航距离', '항속거리'),
    ('甲板装甲', '갑판장갑'),
    ('深水炸弹', '폭뢰'),
    ('排水量', '배수량'),
    ('俯冲轰炸机', '급강하 폭격기'),
    ('干货船', '화물선'),
    ('干船坞', '건선거'),
    ('护航', '호위'),
    ('战斗机', '전투기'),
    ('旗舰', '기함'),
    ('飞行甲板', '비행갑판'),
    ('水雷战队', '수뢰전대'),
    ('飞行艇', '비행정'),
    ('满载排水量', '만재배수량'),
    ('烟囱', '연돌'),
    ('船体', '선체'),
    ('节', '노트'),
    ('下水', '진수'),
    ('首舰', '네임십'),
    ('机枪', '기총'),
    ('主力舰队（后排）', '주력함대'),
    ('主炮', '주포'),
    ('桅杆', '마스트'),
    ('同名舰', '동명함'),
    ('舰炮射击', '함포사격'),
    ('油船', '유조선'),
    ('巡逻', '초계'),
    ('雷达', '레이더'),
    ('侦察', '정찰'),
    ('侦察机', '정찰기'),
    ('改装', '개장'),
    ('自沉', '자침'),
    ('水上飞机', '수상기'),
    ('探照灯', '탐조등'),
    ('副炮', '부포'),
    ('造船厂', '조선소'),
    ('姐妹舰', '자매함'),
    ('声呐', '소나'),
    ('航速', '속력'),
    ('战队', '전대'),
    ('标准排水量', '기준배수량'),
    ('舰尾', '함미'),
    ('击沉', '격침'),
    ('特混舰队', '태스크 포스'),
    ('吨位', '톤수'),
    ('鱼雷', '어뢰'),
    ('鱼雷机', '뇌격기'),
    ('鱼雷发射管', '어뢰발사관'),
    ('炮塔', '포탑'),
    ('先锋舰队（前排）', '선봉함대'),
    ('船坞', '도크'),
    ('型', '형'),
    ('反潜', '대잠'),
    ('机动部队', '기동부대'),
    ('级', '급'),
    # factions / hull prefixes
    ('东煌', '동황'),
    ('白鹰', '이글 유니온'),
    ('自由法国海军（自由鸢尾）', '자유 프랑스 해군'),
    ('英国皇家海军（皇家）', '영국 왕립 해군'),
    ('荷兰皇家海军（郁金王国）', '네덜란드 왕립 해군'),
    ('旧日本海军（重樱）', '일본 제국 해군'),
    ('自由鸢尾', '아이리스 리브르'),
    ('铁血', '메탈 블러드'),
    ('郁金王国', '튤리파 왕국'),
    ('德国海军（铁血）', '독일 해군'),
    ('META', 'META'),
    ('法国海军（维希教廷）', '프랑스 해군'),
    ('飓风船团', '템페스타'),
    ('北方联合', '북방연합'),
    ('意大利皇家海军（撒丁帝国）', '이탈리아 왕립 해군'),
    ('皇家', '로열 네이비'),
    ('重樱', '사쿠라 엠파이어'),
    ('撒丁帝国', '사르데냐 제국'),
    ('塞壬', '세이렌'),
    ('德意志帝国海军', '독일 제국 해군'),
    ('苏联海军（北方联合）', '소련 해군'),
    ('通用型', '범용형'),
    ('美国海军（白鹰）', '미합중국 해군'),
    ('维希教廷', '비시아 성좌'),
    ('联合舰队', '연합함대'),
    # ranks
    ('海军上将', '대장'),
    ('海军上校', '대령'),
    ('参谋长', '참모장'),
    ('海军中校', '중령'),
    ('总司令', '총사령관'),
    ('海军准将', '준장'),
    ('海军少尉', '소위'),
    ('海军元帅', '원수'),
    ('海军上尉', '대위'),
    ('海军少校', '소령'),
    ('海军中尉', '중위'),
    ('海军少将', '소장'),
    ('海军中将', '중장'),
    ('中佐（中校）', '중령'),
    ('中将', '중장'),
    ('中尉', '중위'),
    ('元帅', '원수'),
    ('司令长官', '사령장관'),
    ('大佐（上校）', '대령'),
    ('大将', '대장'),
    ('大尉（上尉）', '대위'),
    ('少佐（少校）', '소령'),
    ('少将', '소장'),
    ('少尉', '소위'),
]

_CATEGORY_OF = {}
for _lng, _src, _zh, _cat in TERMS:
    _CATEGORY_OF.setdefault(_zh, _cat)

_missing = [zh for zh, ko in KO_TERMS if zh not in _CATEGORY_OF]
if _missing:
    raise SystemExit('KO_TERMS references unknown concepts: %s' % _missing)

for _zh, _ko in KO_TERMS:
    TERMS.append(('ko', _ko, _zh, _CATEGORY_OF[_zh]))
