const fs=require('fs'),path=require('path');
const MAIN='E:/Download/BT/Codex_input/genshin-glossary';
const SUP='E:/Download/BT/Codex_input/genshin-glossary-supplement';
const counts=JSON.parse(fs.readFileSync(path.join(MAIN,'_counts.json'),'utf8'));
const langNames={ 'zh-CN':'简体中文','zh-TW':'繁體中文','en-US':'English','ja-JP':'日本語','ko-KR':'한국어','fr-FR':'Français','de-DE':'Deutsch','es-ES':'Español','ru-RU':'Русский','pt-BR':'Português','it-IT':'Italiano','tr-TR':'Türkçe','th-TH':'ภาษาไทย','vi-VN':'Tiếng Việt' };
const langOrder=Object.keys(langNames);
const catOrder=['characters','talents','constellations','weapons','materials','foods','crafts','artifacts','domains','enemies','animals','outfits','windgliders','namecards','geographies','achievements','adventureranks'];
const tcgOrder=['action-cards','character-cards','enemy-cards','summons','status-effects','keywords','card-backs','card-boxes','detailed-rules','level-rewards'];
const concepts=counts.concepts;
const byCode={}; for(const l of counts.languages) byCode[l.code]=l;

function header(t){ return '| source | target | tgt_lng |\n| --- | --- | --- |\n| Enterprise | 企业 | zh-CN |\n| エンタープライズ | 企业 | zh-CN |\n'; }

let md = [];
md.push('# 原神（Genshin Impact）多语言术语库');
md.push('');
md.push('按**目标语言**拆分为独立文件夹，每个文件夹内按**类目**分文件存放。');
md.push('');
md.push('## 数据来源');
md.push('');
md.push('- 主词库：[theBowja/genshin-db](https://github.com/theBowja/genshin-db)（数据版本 7.0，覆盖全部 14 种语言）');
md.push('- 补充词库：见同级目录 `genshin-glossary-supplement/`（来源 [xicri/genshin-langdata](https://github.com/xicri/genshin-langdata)，覆盖 zh-CN / zh-TW / en-US / ja-JP）');
md.push('');
md.push('## 目录结构');
md.push('');
md.push('```');
md.push('genshin-glossary/');
md.push('├── zh-CN/                    # 目标语言 = 简体中文');
md.push('│   ├── characters.csv');
md.push('│   ├── talents.csv');
md.push('│   ├── ...');
md.push('│   └── TCG/                  # TCG 类目按子类型细分');
md.push('│       ├── action-cards.csv');
md.push('│       └── ...');
md.push('├── zh-TW/');
md.push('├── en-US/ ... vi-VN/         # 共 14 个语言文件夹');
md.push('└── _counts.json              # 各语言、各类目的条目数统计');
md.push('```');
md.push('');
md.push('## 文件格式');
md.push('');
md.push('所有 CSV 均为 **UTF-8（含 BOM）** 编码、**CRLF** 换行、首行为表头，字段含逗号或引号时按 RFC 4180 加引号转义。');
md.push('');
md.push(header());
md.push('含义：对于 `tgt_lng` 指定的目标语言，`target` 是译文，`source` 是**其它任一语言**的原文。');
md.push('即每个语言文件夹内，同一条目会以其余 13 种语言分别作为 `source` 各出现一行（重复行与同形行已合并）。');
md.push('');
md.push('## 语言代码');
md.push('');
md.push('| 语言文件夹 | 语言 | genshin-db 内部名 |');
md.push('| --- | --- | --- |');
const dbName={'zh-CN':'ChineseSimplified','zh-TW':'ChineseTraditional','en-US':'English','ja-JP':'Japanese','ko-KR':'Korean','fr-FR':'French','de-DE':'German','es-ES':'Spanish','ru-RU':'Russian','pt-BR':'Portuguese','it-IT':'Italian','tr-TR':'Turkish','th-TH':'Thai','vi-VN':'Vietnamese'};
for(const c of langOrder) md.push(`| \`${c}\` | ${langNames[c]} | ${dbName[c]} |`);
md.push('');
md.push('## 类目与条目数');
md.push('');
md.push('「条目」指该分类下的**去重词条数**（一个词条 = 游戏中的一个名称对象）；「行数」为每个语言文件夹内该类目 CSV 的数据行数。');
md.push('');
md.push('### 主类目');
md.push('');
md.push('| 类目 | 文件 | 词条数 | 每语言行数（约） |');
md.push('| --- | --- | --- | --- |');
for(const c of catOrder){
  const vals=langOrder.map(l=>byCode[l].categories[c]).filter(v=>v!==undefined);
  const avg=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);
  md.push(`| ${c} | \`${c}.csv\` | ${concepts[c]} | ${avg.toLocaleString()} |`);
}
md.push('| TCG | `TCG/*.csv` | ' + tcgOrder.reduce((a,t)=>a+concepts[t],0) + ' | ' + Math.round(langOrder.reduce((a,l)=>a+byCode[l].tcgRows,0)/14).toLocaleString() + ' |');
md.push('');
md.push('### TCG 子类目');
md.push('');
md.push('| 子类目 | 文件 | 词条数 |');
md.push('| --- | --- | --- |');
for(const t of tcgOrder) md.push(`| ${t} | \`TCG/${t}.csv\` | ${concepts[t]} |`);
md.push('');
md.push('## 各语言总行数');
md.push('');
md.push('| 语言 | 文件数 | 数据行数 |');
md.push('| --- | --- | --- |');
let grand=0; const fileCount = catOrder.length + tcgOrder.length;
for(const c of langOrder){ const l=byCode[c]; grand+=l.rows; md.push(`| \`${c}\` | ${fileCount} | ${l.rows.toLocaleString()} |`); }
md.push(`| **合计** | **${fileCount*14}** | **${grand.toLocaleString()}** |`);
md.push('');
md.push('> 跨类目存在同名词条（例如某武器名同时出现在 `weapons` 与 `TCG` 中），因此各文件行数相加会大于全局去重后的词条数，属正常现象。全局唯一 `source/target/tgt_lng` 组合数约为 1,065,154。');
md.push('');
md.push('## 数据清洗说明');
md.push('');
md.push('源数据中的以下标记已在生成时处理：');
md.push('');
md.push('| 源数据写法 | 处理方式 | 示例 |');
md.push('| --- | --- | --- |');
md.push('| `{M#...}{F#...}` 相邻的性别变体 | 取男性形态 | `{M#du débutant}{F#de la débutante}` → `du débutant` |');
md.push('| 单独的 `{M#…}` / `{F#…}` | 取其内容 | `#Искатель{F#ница}` → `Искательница` |');
md.push('| 名称开头的 `#`（性别相关标记） | 去除 | `#Éclaireuse 100%` → `Éclaireuse 100%` |');
md.push('| `{NON_BREAK_SPACE}`、`{SPACE}` | 替换为普通空格 | `PB{NON_BREAK_SPACE}-{NON_BREAK_SPACE}Retorno` → `PB - Retorno` |');
md.push('| 其它占位符（保留原样） | `{NICKNAME}`、`{REALNAME[…]} `、`{MATEAVATAR#SEXPRO[…]} ` | 各仅 1 条 |');
md.push('');
md.push('同名同译文的重复行（例如英/法/德同形的人名）已合并。');
md.push('');
md.push('## 使用提示');
md.push('');
md.push('- 导入 CAT 工具（Trados、memoQ、Phrase 等）时，选择对应目标语言的 CSV 直接作为术语库导入即可。');
md.push('- 文件名即类目名，可按需合并；如需「全部类目合并为单一文件」或增加 `src_lng`（源语言）列，可随时生成。');
md.push('');
fs.writeFileSync(path.join(MAIN,'README.md'), md.join('\n'), 'utf8');
console.log('main README written,', md.length, 'lines');
